### ISSUE TITLE
 README doesn't link format specification

### ISSUE THREAD

**Issue by JonasT** [groupon/cson-parser#61] opened 2017-04-09 19:38 UTC
The README doesn't link a format specification (at least as far as I can see). Please add a link with a complete formal specification of the format comparable to https://tools.ietf.org/html/rfc7159 , preferably also an additional one with some neat easily understandable format e.g. like the flow graphs presented on http://www.json.org/ .

I assume people who know CoffeeScript well can "guess" the format, but that's neither optimal nor is it gonna help others who think about adopting it.

Note: this issue was originally reported here: https://github.com/bevry/cson/issues/77

**Comment by ageitgey** [comment] 2017-04-09 19:46
I believe this is a duplicate of #26 (which is still an open issue)

**Comment by jkrems** [comment] 2017-04-10 01:56
Yeah, agreed. Once there is a formal spec of the format, we'd definitely also link it in the README etc.. But until someone writes a proper one, the only "spec" is "whatever the coffee-script compiler does".

**Closed by jkrems** 2017-04-10 01:56 UTC
